### ISSUE TITLE
Remove `X-EdX-Api-Key` usage

### ISSUE THREAD

**Issue by asadali145** [mitodl/edx-api-client#103]
### Description/Context

Open edX is going to remove the support of [`X-EdX-Api-Key`](https://github.com/openedx/edx-platform/issues/34039) header. Currently, we are using the `X-EdX-Api-Key` and token authentication both in our client. As per the [initial R&D](https://mitodl.slack.com/archives/G72L6SNHH/p1705391842381199?thread_ts=1704997677.222519&cid=G72L6SNHH), we can safely remove the usage of `X-EdX-Api-Key` and our apps would still work as we use the token authentication in our Apps.

Usages:

- https://github.com/mitodl/edx-api-client/blob/61953498720725dd909fd7cf5c463e2ae268b02e/edx_api/client.py#L47 and the related tests.

### Acceptance Criteria:

- Usage of `X-EdX-Api-Key` is removed safely without an impact on the existing functionality.
- Update docs if needed.

### Related tickets
https://github.com/mitodl/mitxpro/issues/2872
https://github.com/mitodl/mitxonline/issues/2102

**Comment by arslanashraf7** [comment]
@mudassir-hafeez Could you take a look at this before https://github.com/mitodl/mitxpro/issues/2872? These two are associated issues and we should work on this one before the xPRO one.

**Comment by mudassir-hafeez** [comment]
@pdpinch 
After conducting some R&D and testing various endpoints of the edx-api-client (along with xpro), I've discovered a potential impact on the [deactivate_enrollment](https://github.com/mitodl/edx-api-client/blob/master/edx_api/enrollments/__init__.py#L204) API for non-staff users if the EdX-Api-Key is removed.

- It seems the [edx-platform](https://github.com/openedx/edx-platform/blob/master/openedx/core/djangoapps/enrollments/views.py#L809) does not update enrollment (i.e. deactivation) for non-staff users without the X-EdX-Api-Key and raises error, even though it is deprecated, and allows them unless users have staff privileges or an EdX-Api-Key is set.
- The following Xpro features/management commands would be impacted if EdX-Api-Key usage is removed:
   - `defer_enrollment`
   - `refund_enrollment`
   - `transfer_enrollment`
- Some similar features exist in mitxonline, which are subject to the same impact.
I suggest we wait until EdX completely removes the usage of EdX-Api-Key from edx-platform. After that, we can address any necessary fixes or adjustments.

**Comment by pdpinch** [comment]
What is the open edx community plan for addressing this? 

I thought we had already switched mitxonline to use a staff user for enrollments already, so we could the invitation_only setting.

**Comment by arslanashraf7** [comment]
In addition to @pdpinch 's comment, Here are some thoughts from my end:

1. I agree with Peter, We did shift the enrollments to invite only we now use staff tokens to enroll users through API.

Some questions:

1. Do we still use `EdX-Api-Key` while enrolling users through the staff token?
2. If Yes, Does the enrollment work If we remove it? 
3. If enrollments are working without `EdX-Api-Key` and the unenrollments are being performed on behalf of the user's token, can we use the staff token in unenrollment as well?

If we can perform unenroll with staff token and without `EdX-Api-Key`, I think we won't need to worry what edX doesn't with API key.


I'd also like to note that the impact of any changes we make in edx-api-client would not be limited to MIT xPRO, It would also touch MITx Online since that uses the same client for API calls to edX.

**Comment by asadali145** [comment]
**Update**

We(Me, Muddassir, and Arslan) discussed the enrollments. Here are the notes of the discussion and steps forward:

- We already moved to the forced enrollments using the staff user and enabled the invitation-only flag for the course enrollments in xPro and MITx Online.
- Enrollments are created using the staff user but we found that `unenrollment` is using the `EdX-Api-Key` and the user token. Arslan has suggested that we use the staff user for the unenrollments as well (Which should be easy to do).

### Next Steps

- Use staff user for the unenrollments
- Remove EdX-Api-Key

CC: @pdpinch @arslanashraf7 @mudassir-hafeez

**Comment by mudassir-hafeez** [comment]
Closing [#103](https://github.com/mitodl/edx-api-client/issues/103) as [PR #104](https://github.com/mitodl/edx-api-client/pull/104) and related PRs (https://github.com/mitodl/mitxpro/pull/2982 and https://github.com/mitodl/mitxonline/pull/2217) have been deployed to production.
