### ISSUE TITLE
add a static method for `passed` to the Certificate class

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-api-client#30]
Part of mitodl/micromasters#2538 

The status attribute of a course certificate indicates whether the user passed the course or not. To aid in upstream processing, we'll add a static method to Certificate class to make it clear whether the learner passed or not. 

edX does not currently expose this status in their certificates API, so we'll have to duplicate the code from https://github.com/edx/edx-platform/blob/master/lms/djangoapps/certificates/models.py#L76-L111

**Comment by pdpinch** [comment]
edX recently added a passed value to the data returned by the certificates API. We should update our client to collect this data and pass it along.

**Comment by amir-qayyum-khan** [comment]
made PR https://github.com/mitodl/edx-api-client/pull/31
