### ISSUE TITLE
Update requirements.txt to support a range of requests library instead of one fixed version

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/edx-api-client#39]
The current `requirements.txt` is fixed to a single version of the `requests` library. This can cause conflicts when using `pip-compile` if another library were to also be so restrictive. Unless we have a strong reason to only require this specific version, I'd suggest we widen the dependency using other operators like `<=`, `>=`, `<`, `>`, etc.

**Comment by pdpinch** [comment]
Is there a best practice about testing with a range of dependency versions?
