### ISSUE TITLE
Add support for bulk grade API

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-api-client#41]
edX recently merged an update to grades API making it possible to get grades in bulk. 

See https://github.com/edx/edx-platform/pull/17602

We would like to use this API with MicroMasters in order to reduce the overhead of things like freezing grades and our periodic grade updates.

**Comment by pdpinch** [comment]
I wonder if we might be able to use this as well as a proxy for enrollments. Do users who are enrolled but haven't answered any problems get a grade?

**Comment by jcdyer** [comment]
I've added myself to the MIT-ODL organization, but still don't have permission to assign this to myself.  Regardless, I will be addressing this issue during the coming two week sprint.

**Comment by pdpinch** [comment]
Sorry about that @jcdyer. I'll take some of the blame for that, but I do want to share with github's teams UI. 

Good to have you working on this!
