### ISSUE TITLE
Add support for the edX account API

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/edx-api-client#44]
We current use the `user_info` api, which provides very limited user information. The `/api/user/v1/me` API is newer and provides much more detailed information. Particularly we have an immediate need to know the user `is_active` value.

The implementation is here: https://github.com/edx/edx-platform/blob/bab76429e25c475215429856b49b3c36eb41e657/openedx/core/djangoapps/user_api/accounts/views.py#L116

We have an existing call against this for MM here: https://github.com/mitodl/micromasters/blob/328cce59ae5a9ff28850a9fff00f309bf187017d/backends/pipeline_api.py#L70-L75

**Comment by pdpinch** [comment]
I don't think we want to do this any more? If I'm wrong, someone can re-open this.
