### ISSUE TITLE
Fix edX API key usage for enrollments

### ISSUE THREAD

**Issue by gsidebo** [mitodl/edx-api-client#57]
PR #55 added the ability to enroll a user in a course "privileged" mode (e.g.: `verified` instead of `audit`). Unfortunately that was done with the faulty assumption that the user access token should be the same as the edx API key in the request headers. The API key is not user-specific – it should have the same value in the API client requests regardless of which user's behalf it is making those requests. Access tokens = user-specific. API key = non-user-specific. This needs to be fixed to get enrollments working correctly for all users

**Comment by kaizoku** [comment]
@gsidebo I created a PR (#58) which fixes this by allowing users of the `edx_api` package to specify an API key in the credentials.
